### PR TITLE
Prototype Merger

### LINKED ISSUE #5: Set routes to accept requests
Setup routes to accept requests from the client.

- [ ] perform OCR on passed image
- [ ] run code and return code executing response.

### LINKED ISSUE #8: Additional Features
These enhancements are meant to be solved after the first stable deployment of the whole project

- [ ] Jest tests setup, with good coverage
- [ ] Setup API documentation gen (Docsify, Postman or any other)
...

### PR DESCRIPTION
**Pull request by YashKumarVerma**
Fixes #5 
Fixes #8 

- [x] Include works from #7 
- [x] Required changes from #7 
- [x] Tests added

### CODE REVIEW

**Comment by YashKumarVerma** [comment]
Tests failing as env not set. Please check

**Comment by sauravhiremath** [comment]
@YashKumarVerma I don't understand why u went through the pain of writing the whole program again. As discussed I had already added the working code on develop branch, any specific reasons for this?

As mentioned in the issue, only adding tests were remaining

**Comment by YashKumarVerma** [comment]
Don't worry 🙃 I didn't write the logic again, it's the same as your branch.

Just added tests and removed a component.

**Comment by sauravhiremath** [comment]
Okay then. I'll remove tests run from CI, as we will be running this locally anyways. Other than that it seems good. Could you merge your changes to develop branch

**Comment by YashKumarVerma** [comment]
> Could you remove the 'Run test' part from `pr.yml` and `build.yml`?

There's one pre-build.yml I could find. where are pr and build.yml ??

**Comment by sauravhiremath** [comment]
Sorry my bad. It's pre-build.yml

**Comment by YashKumarVerma** [comment]
> Sorry my bad. It's pre-build.yml

I guess it's safe now to remove uploadToCloudinary right ?

**Comment by sauravhiremath** [comment]
> > Sorry my bad. It's pre-build.yml
> 
> I guess it's safe now to remove uploadToCloudinary right ?

I think we can keep it. Will be useful if its decided to add in last moment.

Can clean up once the submission is done

**Pull request merged**
